[package]
name = "model_compilator"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.4.0"
ndarray = "0.17.1"
rand = "0.9.2"
rand_distr = "0.5.1"
serde = {version="1.0.228", features = ["derive"]}
serde_json = "1.0.104"
